/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SlmFigure {
    'figPath': string;
    'figPlaceHolder': string;
    'figTitle': string;
  }
  interface SlmGallery {
    'JSON_results': { title: string; path: string }[];
    'galleryDescription': string;
    'galleryItemPlaceHolder': string;
    'galleryTitle': string;
  }
}

declare global {


  interface HTMLSlmFigureElement extends Components.SlmFigure, HTMLStencilElement {}
  var HTMLSlmFigureElement: {
    prototype: HTMLSlmFigureElement;
    new (): HTMLSlmFigureElement;
  };

  interface HTMLSlmGalleryElement extends Components.SlmGallery, HTMLStencilElement {}
  var HTMLSlmGalleryElement: {
    prototype: HTMLSlmGalleryElement;
    new (): HTMLSlmGalleryElement;
  };
  interface HTMLElementTagNameMap {
    'slm-figure': HTMLSlmFigureElement;
    'slm-gallery': HTMLSlmGalleryElement;
  }
}

declare namespace LocalJSX {
  interface SlmFigure {
    'figPath'?: string;
    'figPlaceHolder'?: string;
    'figTitle'?: string;
  }
  interface SlmGallery {
    'JSON_results'?: { title: string; path: string }[];
    'galleryDescription'?: string;
    'galleryItemPlaceHolder'?: string;
    'galleryTitle'?: string;
  }

  interface IntrinsicElements {
    'slm-figure': SlmFigure;
    'slm-gallery': SlmGallery;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'slm-figure': LocalJSX.SlmFigure & JSXBase.HTMLAttributes<HTMLSlmFigureElement>;
      'slm-gallery': LocalJSX.SlmGallery & JSXBase.HTMLAttributes<HTMLSlmGalleryElement>;
    }
  }
}


